### ISSUE TITLE
Fix "gatsby: not found" error in ocean.py Quickstart Marketplace Flow

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/contracts#278]
In the ocean.py Quickstart: Marketplace Flow, I ran into the following error. This issue will track the investigation of why this error occurred.

I've attached my full terminal log for reference. [https://app.zenhub.com/files/248724103/46dd6536-7849-4221-b422-7f4b5017b1c0/download](https://app.zenhub.com/files/248724103/46dd6536-7849-4221-b422-7f4b5017b1c0/download)

```
david@david-Inspiron-5502:~/projects/market$ npm start

> @oceanprotocol/market@1.0.0 start /home/david/projects/market
> gatsby develop --host 0.0.0.0

sh: 1: gatsby: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @oceanprotocol/market@1.0.0 start: `gatsby develop --host 0.0.0.0`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @oceanprotocol/market@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2021-03-18T21_12_31_846Z-debug.log
david@david-Inspiron-5502:~/projects/market$ cat /home/david/.npm/_logs/2021-03-18T21_11_57_048Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @oceanprotocol/market@1.0.0~prestart: @oceanprotocol/market@1.0.0
6 info lifecycle @oceanprotocol/market@1.0.0~start: @oceanprotocol/market@1.0.0
7 verbose lifecycle @oceanprotocol/market@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle @oceanprotocol/market@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/david/projects/market/node_modules/.bin:/home/david/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @oceanprotocol/market@1.0.0~start: CWD: /home/david/projects/market
10 silly lifecycle @oceanprotocol/market@1.0.0~start: Args: [ '-c', 'gatsby develop --host 0.0.0.0' ]
11 info lifecycle @oceanprotocol/market@1.0.0~start: Failed to exec start script
12 verbose stack Error: @oceanprotocol/market@1.0.0 start: `gatsby develop --host 0.0.0.0`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid @oceanprotocol/market@1.0.0
14 verbose cwd /home/david/projects/market
15 verbose Linux 5.8.0-45-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v10.19.0
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error @oceanprotocol/market@1.0.0 start: `gatsby develop --host 0.0.0.0`
23 error spawn ENOENT
24 error Failed at the @oceanprotocol/market@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by DMats** [comment]
The error was caused by me skipping the `npm install` step.  In my mind, I conflated it with `apt install npm`.
