### ISSUE TITLE
Ropsten & Mumbai deployments are failing

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/contracts#496]
node scripts/deploy-contracts.js 
Using RPC: https://ropsten.infura.io/v3/XXX
Using chain 3
Use existing addresses:{}
Deploying OPF Community Fee
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0x7842Fa3B2d87Ff1cd52C4152382f7C4B3406E5A6 0x58F76AE5BC7Fe80D2fb2781d92189e6eE6Eb8F76 0x58F76AE5BC7Fe80D2fb2781d92189e6eE6Eb8F76
Deploying V4 contracts
Deploying BPool
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0x973e69303259B0c2543a38665122b773D28405fB
Deploying Router
	Run the following to verify on etherscan
	cat > args1.js

	module.exports=[

	'0xC7EC1970B09224B317c52d92f37F5e1E4fF6B687',

	'0x5e8DCB2AfA23844bcc311B00Ad1A0C30025aADE9',

	'0x973e69303259B0c2543a38665122b773D28405fB',

	'0x7842Fa3B2d87Ff1cd52C4152382f7C4B3406E5A6',

	[]

	];
	CTRL+D
	npx hardhat verify --network ropsten --constructor-args args1.js 0x3E85e7Cb15880b6d4871092E74bF65CE03E8448D
Deploying FixedrateExchange
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0x4344D4Bc29531DB736378e9A3dA85BF1eff0CB22 0x3E85e7Cb15880b6d4871092E74bF65CE03E8448D 0x7842Fa3B2d87Ff1cd52C4152382f7C4B3406E5A6
Deploying StakingContract
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0x8bA04715B1b210f710426b21A29887EEd4EA6751 0x3E85e7Cb15880b6d4871092E74bF65CE03E8448D
Deploying ERC20 Template
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0x1706DF1f2d93558D1d77bEd49ccdB8B88fAfC306
Deploying ERC20 Enterprise Template
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0x45dA5988d4fEAEdc5Ee60FC83eA7Caa8Fb485883
Deploying ERC721 Template
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0xA8513c0457AfaD54a57664Ba5C742c24f1D624be
Deploying Dispenser
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0xDB55DCBbAC940aCb5c28817802f17A48B15d558b 0x3E85e7Cb15880b6d4871092E74bF65CE03E8448D
Deploying ERC721 Factory
{
  ERC721: '0xA8513c0457AfaD54a57664Ba5C742c24f1D624be',
  ERC20: '0x1706DF1f2d93558D1d77bEd49ccdB8B88fAfC306',
  OPFCommunityFeeCollector: '0x7842Fa3B2d87Ff1cd52C4152382f7C4B3406E5A6',
  Router: '0x3E85e7Cb15880b6d4871092E74bF65CE03E8448D'
}
	Run the following to verify on etherscan
	npx hardhat verify --network ropsten 0x042BFbd88c3998282153088604207b2AeF045b43 0xA8513c0457AfaD54a57664Ba5C742c24f1D624be 0x1706DF1f2d93558D1d77bEd49ccdB8B88fAfC306 0x7842Fa3B2d87Ff1cd52C4152382f7C4B3406E5A6 0x3E85e7Cb15880b6d4871092E74bF65CE03E8448D
Adding ERC20Enterprise to ERC721Factory
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":438,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8910344849502f9008505e70eb0e48401bad9d894042bfbd88c3998282153088604207b2aef045b4380a47b20bccf00000000000000000000000045da5988d4feaedc5ee60fc83ea7caa8fb485883c080a06bee413839590b314e6904194a95246a6e2d8e40c57ebb14860c1f1744a61122a055dd2285c5789c748ed42513da9c449ed1d5ca1e292c575e36911c41d2592633\"],\"id\":438,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://ropsten.infura.io/v3/XXX", code=SERVER_ERROR, version=web/5.5.0)
    at Logger.makeError (/ocean/contracts_v4/contracts/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/ocean/contracts_v4/contracts/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at /ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:266:32
    at step (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":438,"error":{"code":-32000,"message":"exceeds block gas limit"}}',
  error: Error: exceeds block gas limit
      at getResult (/ocean/contracts_v4/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)
      at processJsonFunc (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:309:22)
      at /ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:241:46
      at step (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5) {
    code: -32000,
    data: undefined
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0x02f8910344849502f9008505e70eb0e48401bad9d894042bfbd88c3998282153088604207b2aef045b4380a47b20bccf00000000000000000000000045da5988d4feaedc5ee60fc83ea7caa8fb485883c080a06bee413839590b314e6904194a95246a6e2d8e40c57ebb14860c1f1744a61122a055dd2285c5789c748ed42513da9c449ed1d5ca1e292c575e36911c41d2592633"],"id":438,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://ropsten.infura.io/v3/XXX',
  transaction: {
    type: 2,
    chainId: 3,
    nonce: 68,
    maxPriorityFeePerGas: BigNumber { _hex: '0x9502f900', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x05e70eb0e4', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x01bad9d8', _isBigNumber: true },
    to: '0x042BFbd88c3998282153088604207b2AeF045b43',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x7b20bccf00000000000000000000000045da5988d4feaedc5ee60fc83ea7caa8fb485883',
    accessList: [],
    hash: '0xbe77ab7eede1e3d925f0eca877a51e807d68378ec6135dc19da1ef4bf960c986',
    v: 0,
    r: '0x6bee413839590b314e6904194a95246a6e2d8e40c57ebb14860c1f1744a61122',
    s: '0x55dd2285c5789c748ed42513da9c449ed1d5ca1e292c575e36911c41d2592633',
    from: '0xC7EC1970B09224B317c52d92f37F5e1E4fF6B687',
    confirmations: 0
  },
  transactionHash: '0xbe77ab7eede1e3d925f0eca877a51e807d68378ec6135dc19da1ef4bf960c986'
}

Mumbai:
node scripts/deploy-contracts.js 
Using RPC: https://polygon-mumbai.infura.io/v3/XXX
Using chain 80001
Use existing addresses:{}
Deploying OPF Community Fee
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0x8389bC1306208488D665F939AFB4079adf6f5a06 0x06100AB868206861a4D7936166A91668c2Ce1312 0x06100AB868206861a4D7936166A91668c2Ce1312
Deploying V4 contracts
Deploying BPool
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0xc97fa83746aDe91b0eeB16cb51326a0A980Af7c3
Deploying Router
	Run the following to verify on etherscan
	cat > args1.js

	module.exports=[

	'0xC7EC1970B09224B317c52d92f37F5e1E4fF6B687',

	'0xd8992Ed72C445c35Cb4A2be468568Ed1079357c8',

	'0xc97fa83746aDe91b0eeB16cb51326a0A980Af7c3',

	'0x8389bC1306208488D665F939AFB4079adf6f5a06',

	[]

	];
	CTRL+D
	npx hardhat verify --network mumbai --constructor-args args1.js 0xE5aa2C9B551aFcA4C0A98BB3B37D7A43084d0a66
Deploying FixedrateExchange
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0xf0c7A31D7Ee26bEBfb4BAD8e37490bEadE3F846f 0xE5aa2C9B551aFcA4C0A98BB3B37D7A43084d0a66 0x8389bC1306208488D665F939AFB4079adf6f5a06
Deploying StakingContract
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0xA0329eFFa1370eAb1DC5998Db4292ae0F535a282 0xE5aa2C9B551aFcA4C0A98BB3B37D7A43084d0a66
Deploying ERC20 Template
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0x0Ee8b03Dafc868a0899ebE1c12d734D53A957250
Deploying ERC20 Enterprise Template
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0x86F2BB9F8f18B5a836b342199a3eC89F282E4018
Deploying ERC721 Template
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0xe47991939632757DEe324E8ec9A3268c62C0DB76
Deploying Dispenser
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0x4D49eEedFac8Ea03328c0E4871b680C06d892092 0xE5aa2C9B551aFcA4C0A98BB3B37D7A43084d0a66
Deploying ERC721 Factory
{
  ERC721: '0xe47991939632757DEe324E8ec9A3268c62C0DB76',
  ERC20: '0x0Ee8b03Dafc868a0899ebE1c12d734D53A957250',
  OPFCommunityFeeCollector: '0x8389bC1306208488D665F939AFB4079adf6f5a06',
  Router: '0xE5aa2C9B551aFcA4C0A98BB3B37D7A43084d0a66'
}
	Run the following to verify on etherscan
	npx hardhat verify --network mumbai 0xAEf06d8507F884674EC70330f4FBd21E23792D88 0xe47991939632757DEe324E8ec9A3268c62C0DB76 0x0Ee8b03Dafc868a0899ebE1c12d734D53A957250 0x8389bC1306208488D665F939AFB4079adf6f5a06 0xE5aa2C9B551aFcA4C0A98BB3B37D7A43084d0a66
Adding ERC20Enterprise to ERC721Factory
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":286,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f893830138812c849502f900849502f9148401bad9d894aef06d8507f884674ec70330f4fbd21e23792d8880a47b20bccf00000000000000000000000086f2bb9f8f18b5a836b342199a3ec89f282e4018c080a0d32f879927037bd40153d135166da36c680f313e835cde43a6e549b267be6da8a0318576d8efccd98d09e76629830c53d071a415344409209e9e6a2ee553ecdf5d\"],\"id\":286,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://polygon-mumbai.infura.io/v3/XXX", code=SERVER_ERROR, version=web/5.5.0)
    at Logger.makeError (/ocean/contracts_v4/contracts/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/ocean/contracts_v4/contracts/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at /ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:266:32
    at step (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":286,"error":{"code":-32000,"message":"exceeds block gas limit"}}',
  error: Error: exceeds block gas limit
      at getResult (/ocean/contracts_v4/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)
      at processJsonFunc (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:309:22)
      at /ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:241:46
      at step (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/ocean/contracts_v4/contracts/node_modules/@ethersproject/web/lib/index.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:94:5) {
    code: -32000,
    data: undefined
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0x02f893830138812c849502f900849502f9148401bad9d894aef06d8507f884674ec70330f4fbd21e23792d8880a47b20bccf00000000000000000000000086f2bb9f8f18b5a836b342199a3ec89f282e4018c080a0d32f879927037bd40153d135166da36c680f313e835cde43a6e549b267be6da8a0318576d8efccd98d09e76629830c53d071a415344409209e9e6a2ee553ecdf5d"],"id":286,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://polygon-mumbai.infura.io/v3/XXX',
  transaction: {
    type: 2,
    chainId: 80001,
    nonce: 44,
    maxPriorityFeePerGas: BigNumber { _hex: '0x9502f900', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x9502f914', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x01bad9d8', _isBigNumber: true },
    to: '0xAEf06d8507F884674EC70330f4FBd21E23792D88',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x7b20bccf00000000000000000000000086f2bb9f8f18b5a836b342199a3ec89f282e4018',
    accessList: [],
    hash: '0x6cfc374ac15938efdd2609a7a53439e3ce4b53b6520797e482b28697f07a6273',
    v: 0,
    r: '0xd32f879927037bd40153d135166da36c680f313e835cde43a6e549b267be6da8',
    s: '0x318576d8efccd98d09e76629830c53d071a415344409209e9e6a2ee553ecdf5d',
    from: '0xC7EC1970B09224B317c52d92f37F5e1E4fF6B687',
    confirmations: 0
  },
  transactionHash: '0x6cfc374ac15938efdd2609a7a53439e3ce4b53b6520797e482b28697f07a6273'
}

**Comment by alexcos20** [comment]
Fixed by @lacoop6tu.  Changes merged in https://github.com/oceanprotocol/contracts/pull/507
