### ISSUE TITLE
Error deploying smart contracts in barge's development network

### ISSUE THREAD

**Issue by rogargon** [oceanprotocol/contracts#672]
**Describe the bug**

The smart contracts are not correctly deployed when using the last version of Barge, which uses oceanprotocol/ocean-contracts:v1.0.0

The deployment process stops with the following error:

```
Deploying FixedrateExchange
Error: invalid address or ENS name (argument="name", value={"gasLimit":8000000}, code=INVALID_ARGUMENT, version=contracts/5.6.0)
    at Logger.makeError (/ocean-contracts/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/ocean-contracts/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at Logger.throwArgumentError (/ocean-contracts/node_modules/@ethersproject/logger/lib/index.js:245:21)
    at /ocean-contracts/node_modules/@ethersproject/contracts/lib/index.js:94:32
    at step (/ocean-contracts/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/ocean-contracts/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/ocean-contracts/node_modules/@ethersproject/contracts/lib/index.js:20:58) {
  reason: 'invalid address or ENS name',
  code: 'INVALID_ARGUMENT',
  argument: 'name',
  value: { gasLimit: 8000000 }
}
```

The deployment process doesn't complete so address.json is not updated with the addresses of the smart contracts.

**To Reproduce**
1. git clone git@github.com:oceanprotocol/barge.git
2. cd barge
3. ./start_ocean.sh  --with-thegraph

**Expected behavior**
The smart contracts are deployed and the address for all contracts on the development network (8996) are updated on `/ocean-contracts/artifacts/address.json`

**Comment by alexcos20** [comment]
please delete $HOME/.ocean/*  before running barge
most likely you already have the folder created by barge v3

**Comment by rogargon** [comment]
Thanks, @alexcos20, now the contracts are deployed. Tried to make the market work with a local deployment of Barge. Now the issue is with Aquarius not indexing the MetadataCreated event. I will report it on the Aquarius repository.
